bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#top'

  get "home/about" => "home#about" , as: "about"

  resources :books
  resources :users, only: [:new, :create, :index, :show, :edit, :update]


end

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class=bg-dark text-white pt-5 pb-4">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container ">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
             <% if user_signed_in? %>
              <li class="fas fa-home nav-link text-light">
              <%= link_to 'Home', user_path(current_user.id) %>
              </li>
              <li class="fas fa-users nav-link text-light">
              <%= link_to 'Users', users_path %>
              </li>
              <li class="fas fa-book-open nav-link text-light">
              <%= link_to 'Books', books_path %>
              </li>
              <li class="fas fa-sign-out-alt nav-link text-light">
              <%= link_to "logout ", destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
              <li class="fas fa-home nav-link text-light">
              <%= link_to 'Home', "/" %>
              </li>
              <li class="fas fa-link nav-link text-light">
              <%= link_to "About", about_path %>
              </li>
              <li class="fas fa-user-plus nav-link text-light">
              <%= link_to "sign up", new_user_registration_path %>
              </li>
              <li class="fas fa-sign-in-alt nav-link text-light">
              <%= link_to "login", new_user_session_path %>
              </li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
<main class="mb-auto">
    <p><%= flash[:notice] %></p>
    <%= yield %>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>