bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#top'

  get "home/about" => "home#about" , as: "about"

  resources :books
  resources :users, only: [:new, :create, :index, :show, :edit, :update]


end

bookers2/app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

validates :title, presence: true
validates :body, presence: true, length: {maximum: 200}
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @new_book = Book.new
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def create
    @books = Book.all
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:success] = 'successfully'
    redirect_to book_path(@new_book.id)
    else
      flash.now[:danger] = 'error'
    render 'books/index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
    render "edit"
    else
    redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'successfully'
    redirect_to book_path(@book.id)
    else
      flash.now[:danger] = 'error'
      render 'books/edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/_book.html.erb
<h1>New book</h1>
<div>
  <%= form_with model:@book, local:true do |f| %>
  <label for="inputTitle">title</label>
   <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title"%>
  <label for="inputBody">Opinion</label>
   <%= f.text_area :body, autofocus: true, id:"inputBody", placeholder:"Opinion"%>

  <%= f.submit "Create Book" %>
<% end %>
</div>

bookers2/app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>Editing Book</h1>
        <%= flash[:success] %>
        <%= flash[:danger] %>

      <% if @book.errors.any? %>
      <p><%= @book.errors.count %>件のエラーが発生しました</p>
      <% @book.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    <% end %>


      <%= form_with model:@book, url:book_path, local: true do |f| %>
        <br>Title</br><%= f.text_field :title %>
        <br>Opinion</br><%= f.text_area :body %>
  
        <p><%= f.submit 'Update Book' %></p>
      <% end %>

      <p><%= link_to "Show", book_path(@book.id) %></p>
      <p><%= link_to "Back", books_path %></p>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= flash[:success] %>
    <%= flash[:danger] %>
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
    <table class="table">
        <thead>
          <tr>
            <th>name</th>
            <td><%= current_user.name %></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>introduction</th>
            <td><%= current_user.introduction %></td>
          </tr>
        </tbody>
      </table>
    <div class="row">
  <%# if @user.id == current_user.id %>
    <button type="button" class="btn btn-outline-secondary btn-block fas fa-user-cog">   
    <%= link_to "プロフィール編集", edit_user_path(current_user) %>
    </button>
  <%# end %>
  </div>

<% if @new_book.errors.any? %>
  <p><%= @new_book.errors.count %>件のエラーが発生しました</p>
  <% @new_book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h2>New book</h2>
<div class="form">
  <%= form_with model:@new_book, local:true do |f| %>
  <br><label for="inputTitle">title</label></br>
   <%= f.text_field :title %>
  <br><label for="inputBody">Opinion</label></br>
   <%= f.text_area :body %>

  <%= f.submit "Create Book" %>
  <% end %>
</div>
</div>


<div class="col-md-8 offset-md-1">
      <h2>Books</h2>


      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
          <th>
          <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
          <% end %>
          </th>
          <th><%= link_to book.title, book_path(book.id) %></th>
          <th><%= book.body %></th>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>


</div>
 

</div>

bookers2/app/views/books/new.html.erb
<h1>New book</h1>
<%= flash[:success] %>
<%= flash[:danger] %>

<div>
  <%= form_with model:@book, local:true do |f| %>
  <label for="inputTitle">title</label>
   <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title"%>
  <label for="inputBody">Opinion</label>
   <%= f.text_area :body, autofocus: true, id:"inputBody", placeholder:"Opinion"%>

  <%= f.submit "Create Book" %>
<% end %>
</div>

bookers2/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= flash[:success] %>
    <%= flash[:danger] %>
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
    <table class="table">
        <thead>
          <tr>
            <th>name</th>
            <td><%= @user.name %></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>introduction</th>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
    <div class="row">
      <button type="button" class="btn btn-outline-secondary btn-block fas fa-user-cog">
   <%# if @book.user.id == current_user.id %>
      <%= link_to "プロフィール編集", edit_user_path(@user) %>
  <%# end %>
      </button>
    </div>

<% if @new_book.errors.any? %>
  <p><%= @new_book.errors.count %>件のエラーが発生しました</p>
  <% @new_bookk.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

  <h2>New book</h2>
  <div class="form">
   <%= form_with model:@new_book, local:true do |f| %>
    <br><label for="inputTitle">title</label></br>
    <%= f.text_field :title %>
    <br><label for="inputBody">Opinion</label></br>
    <%= f.text_area :body %>

   <%= f.submit "Create Book" %>
 <% end %>
</div>
</div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table table-hover table-inverse">
         <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
           </tr>
         </thead>
         <tbody>
           <tr>
           <th>
           <%= link_to user_path(@user) do %>
           <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
           <br><%= @user.name %></br>
           <% end %>
           </th>
           <th><%= @book.title %></th>
           <th><%= @book.body %></th>
          <% if @user.id == current_user.id %>
           <th><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></th>
           <th><%= link_to "Destroy", book_path(), class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></th>
          <% end %>
          </tr>
         </tbody>
      </table>
    </div>
  </div>
</div>



</div>


</div>